version: "3.8"

services:
  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    restart: always
    networks:
      - dokploy-network
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "3001:3000"
    restart: always
    networks:
      - dokploy-network