"""add is_draft to fails

Revision ID: 0ab9ca62ccfb
Revises: 402ec73000c9
Create Date: 2024-12-08 00:08:24.079529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ab9ca62ccfb'
down_revision: Union[str, None] = '402ec73000c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fails', sa.Column('is_draft', sa.Boolean(), nullable=False))
    op.execute("UPDATE fails SET is_draft = TRUE")
    op.alter_column('fails', 'is_draft',
                    existing_type=sa.Boolean(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fails', 'is_draft')
    # ### end Alembic commands ###
