"""Replace is_draft with status

Revision ID: 718e513e0bc4
Revises: 251732678dc6
Create Date: 2024-12-08 17:41:49.481013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '718e513e0bc4'
down_revision: Union[str, None] = '251732678dc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fails', sa.Column('status', sa.Enum('DRAFT', 'CHECKING', 'PUBLISHED', name='failstatus'), nullable=False))
    op.drop_column('fails', 'is_draft')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fails', sa.Column('is_draft', sa.BOOLEAN(), nullable=False))
    op.drop_column('fails', 'status')
    # ### end Alembic commands ###
